### ISSUE TITLE
Support grammar changes in Lilypond 2.18

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#55] opened 2015-04-14 18:40 UTC
```
There might be some breaking changes in 2.18. Please investigate and adapt to 
them.
```

Original issue reported on code.google.com by `harmathdenes` on 2 Jan 2014 at 11:45

**Comment by thSoft** [comment] 2015-06-12 12:48
Duplicate of #58.

**Closed by thSoft** 2015-06-12 12:48 UTC
Labels: auto-migrated, Priority-Medium, Type-Enhancement
