### ISSUE TITLE
Implement full grammar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#49] opened 2015-04-14 18:40 UTC
```
Define the semantic model for all features of LilyPond. Among others, this 
would enable generating scores in a model-based way.
```

Original issue reported on code.google.com by `harmathdenes` on 3 Aug 2012 at 9:39

**Comment by nittka** [comment] 2015-06-12 11:42
Is this a duplicate of #55?

**Comment by thSoft** [comment] 2015-06-12 12:49
Duplicate of #58

**Closed by thSoft** 2015-06-12 12:49 UTC
Labels: auto-migrated, Priority-Medium, Type-Enhancement
