### ISSUE TITLE
Fix text markup commands in grammar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#58] opened 2015-04-14 18:40 UTC
```
Put \trill anywhere into your score, this produces the error message "Unknown 
variable"

What version of the product are you using? On what operating system?
Elysium 0.4.0.201404280105
Lilypond 2.18.2
Windows 7



```

Original issue reported on code.google.com by `sirhenry3591` on 19 Jul 2014 at 7:29

**Comment by nittka** [comment] 2015-06-12 11:41
Can you elaborate on the \markup grammar rule being hacky? I would not like to start from scratch when approaching the problem. Is there any other documentation on the original grammar other than http://lilypond.org/doc/v2.18/Documentation/contributor/lilypond-grammar? Basically, I am jumping into an involved grammar without knowing the language at all.

For this particular issue distinguishing between Assignment and PropertyAssignment or more importantly recognising the end of a markup seem the key. Given Xtext's general workflow of lexing, parsing, indexing, linking, there are several potential starting points.

One dirty hack I could imagine is splitting up the white space rule into white spaces that end with new lines and white spaces that do not end with new lines (i.e. indentation). Hiding them for different rules in the grammar might allow the backtracking to find the correct alternative. This idea is based on the assumption that assignements (that we want to cross reference) are really made on root level and hence the name has no indentation. Or to look at it from the other direction, a property assignment as part of a makro will be properly indented. This would be a syntactic indicator that could be used without changing the grammar completely or implementing the parser completely by hand.

However, splitting up the white space rule is not without risk - especially when it comes to formatting etc.

A completely different approach would be to leave the parser as it is, but adapt the creation of the index (resource description). In case we stumble upon a property assignment, we analyse the object and check if it may not have been a normal assignemt after all and put it into the index.

I guess the best solution would be having a grammar that yields a model where all elements have the correct type, but my feeling tells me that this is way out of scope. Given the above mentioned workflow it may even be next to impossible because it would be necessary to link the model while instantiating the object tree (in order to determine the number of arguments expected, otherwise you might not know if something is a function argument...).

**Comment by thSoft** [comment] 2015-06-12 13:23
Yes, the main problem would be to detect how many arguments a Scheme function has. @wzurborg has made some investigations, but Scheme is very complex. Wernke, could you please describe your findings? Meanwhile I'm trying to document the grammar a bit...

**Comment by thSoft** [comment] 2015-06-12 13:27
Some links that may be relevant:
* http://www.lilypond.org/doc/v2.19/Documentation/extending/markup-functions
* http://www.lilypond.org/doc/v2.19/Documentation/extending/lilypond-scheme-syntax
* http://www.scheme.com/tspl2d/grammar.html

**Comment by nittka** [comment] 2015-06-13 18:07
I have not worked on the full grammar, but first tried to adapt the existing one to work for more cases which worked out pretty. Please try out my grammar changes to be found at

https://github.com/nittka/elysium/blob/markupHack/org.elysium/src/org/elysium/LilyPond.xtext

I added some brief comments in the grammar as well.

**Comment by thSoft** [comment] 2015-06-13 23:43
Wow, the result of the integration test looks awesome with your modifications! Please open a PR for discussing them. In the meantime, I ignored the src-gen folders, I hope collaborating on the grammar will be easier this way.

**Comment by nittka** [comment] 2015-06-14 18:44
Is it correct that the integration test files in snippets come from http://lsr.di.unimi.it/LSR/Search?
I just downloaded the current database and it contains more than 800 files now. Also, the number of failing tests is much higher here. Maybe it is time to update the test cases as well?

**Comment by thSoft** [comment] 2015-06-14 19:31
Not exactly, they are from [the official LilyPond source tree of the latest stable release](http://git.savannah.gnu.org/gitweb/?p=lilypond.git;a=tree;f=Documentation/snippets;h=51e6b50b157e04ab0e64ce08eef0594fcaa21202;hb=c95f13fce772e23b5ba04fc8ea0c80855b069c24) (2.18.2 as of now). I updated them in 9c5248d.

**Comment by thSoft** [comment] 2015-06-14 22:44
Unfortunately, #78 did not fix this issue, \trill, \upbow etc. are still unrecognized.

**Comment by nittka** [comment] 2015-06-15 06:58
Too bad. I did not realize this because I used the local workaround described above - moving the \thumb-definition to the end of the file... I remember saying something about more elaborate regression tests ;-)

When playing around a little more last night, I also saw that single line comments for scheme are actually starting with a single semicolon rather than two. This will be quite a challenge because a single semicolon may well appear in regular LilyPond code (e.g. lyrics).

**Comment by nittka** [comment] 2015-06-15 14:17
I replaced my local script-init.ly with the version from the test project. On my machine \trill and  \upbow are indeed recognized! I guess antlr compiles different parsers on our machines, possibly due to backtracking and timeout settings. Could you try increasing the timeouts in the mwe-file?
If this does not help, we should compare the semantic models calculated from the file.

I still think that not checking in the generated code is the right way to go...

**Comment by thSoft** [comment] 2015-06-16 10:53
Sorry, I regenerated the language infrastructure once again and now \trill etc. work for me too. (I'm sure it was generated last time also, so it might have been some Eclipse caching issue?)

**Comment by thSoft** [comment] 2015-06-20 07:45
Fixd by #78 for now. Full semantic handling of defining markup commands is a larger task, maybe we should reopen #29 when it seems feasible.

**Closed by thSoft** 2015-06-20 07:45 UTC
Labels: auto-migrated, Priority-High, Type-Defect
